### ISSUE TITLE
404 on default.js

### ISSUE THREAD

**Issue by SadiqUltra** [totaljs/flowboardcomponents#2]
I have added flowboard package via /definitions. when I go to /$flowboard page I see menu button is not working.
The issue is `default.js` is pointed at 
[http://MYDOMAIN.COM/default/$flowboard/default.js](http://MYDOMAIN.COM/default/$flowboard/default.js) instead of [http://MYDOMAIN.COM/$flowboard/default.js](http://MYDOMAIN.COM/$flowboard/default.js)

**Comment by petersirka** [comment]
Hi @SadiqUltra, please download Flowboard from my.totaljs.com. I have updated CDN by adding new version, but it takes some time for refreshing.

Thank you!

**Comment by petersirka** [comment]
I fixed this bug some time ago, but I forgot to update CDN.

**Comment by SadiqUltra** [comment]
Thank you very much @petersirka.
