### ISSUE TITLE
Make HTTP call in flowboard application in initial load and add data to designer.json

### ISSUE THREAD

**Issue by shabbir-dhangot** [totaljs/flowboardcomponents#3]
I initially add load data using AJAX and added into designer.json. But when I rerun node debug.js then those code got override. I don't have clue how to make API call for flowboard. Can you help me on this.

**Comment by petersirka** [comment]
Hi, Flowboard reads data from the Flow. Flow and Flowboard uses WebSocket only for comunication. For example:

- making a request: <https://github.com/totaljs/flowboardcomponents/blob/master/light/light.html#L60> emits event here: <https://github.com/totaljs/flowcomponents/blob/master/flowboardlight/flowboardlight.js#L33>
- receiving data in Flowboard <https://github.com/totaljs/flowboardcomponents/blob/master/light/light.html#L35> and sending in Flow: <https://github.com/totaljs/flowcomponents/blob/master/flowboardlight/flowboardlight.js#L55>
